blank_issues_enabled: false
contact_links:
    - name: Questions & Discussions
      url: https://github.com/jamzercise/lidifin/discussions
      about: Ask questions and discuss Lidifin in GitHub Discussions
